import 'rpc/step.pb.dart';

class StepModel {
  static List<StepInfo> data() {
    final list = <StepInfo>[
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 200,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 200,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 200,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 200,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 200,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 200,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 200,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 200,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 200,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 200,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 200,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 200,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 1,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 2,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 3,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 4,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 5,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 6,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 7,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 1,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 2,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 3,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 4,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 5,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 6,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
      StepInfo(
          fileName: '/Users/hello/step/hello.dart',
          file: 'hello.dart',
          sourceStep: 7,
          commentStep: 12,
          totalStep: 312,
          emptyLineStep: 88,
          validStep: 188),
    ];

    return list;
  }
}
