// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package betterstep

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StepClient is the client API for Step service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StepClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*StepReply, error)
}

type stepClient struct {
	cc grpc.ClientConnInterface
}

func NewStepClient(cc grpc.ClientConnInterface) StepClient {
	return &stepClient{cc}
}

func (c *stepClient) SayHello(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*StepReply, error) {
	out := new(StepReply)
	err := c.cc.Invoke(ctx, "/betterstep.Step/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StepServer is the server API for Step service.
// All implementations must embed UnimplementedStepServer
// for forward compatibility
type StepServer interface {
	// Sends a greeting
	SayHello(context.Context, *StepRequest) (*StepReply, error)
	mustEmbedUnimplementedStepServer()
}

// UnimplementedStepServer must be embedded to have forward compatible implementations.
type UnimplementedStepServer struct {
}

func (UnimplementedStepServer) SayHello(context.Context, *StepRequest) (*StepReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedStepServer) mustEmbedUnimplementedStepServer() {}

// UnsafeStepServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StepServer will
// result in compilation errors.
type UnsafeStepServer interface {
	mustEmbedUnimplementedStepServer()
}

func RegisterStepServer(s grpc.ServiceRegistrar, srv StepServer) {
	s.RegisterService(&Step_ServiceDesc, srv)
}

func _Step_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StepServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/betterstep.Step/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StepServer).SayHello(ctx, req.(*StepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Step_ServiceDesc is the grpc.ServiceDesc for Step service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Step_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "betterstep.Step",
	HandlerType: (*StepServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Step_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/step.proto",
}
